export declare type AsyncValue<V = any> = V | (() => V);
export declare type AsyncResolve<V = any> = (value: AsyncValue<V>) => AsyncValue<V>;
export declare type AsyncReject<E = any> = (error: AsyncValue<E>) => AsyncValue<E>;
export declare type AsyncThen<V> = (value: V) => any;
export declare type AsyncFunction<V = any, E = any> = (resolve: AsyncResolve<V>, reject: AsyncReject<E>) => void;
export declare type AsyncEvent = () => any;
export declare type AsyncEventType = 'resolve' | 'reject' | 'update';
export declare type AsyncEvents = Set<AsyncEvent>;
export declare type AsyncEventList = {
    [key: string]: AsyncEvents;
};
export declare type IAsyncOptions<V = any, E = any> = {
    request?: AsyncFunction<V, E>;
    timeout?: number;
    loading?: boolean;
    loaded?: boolean;
    events?: AsyncEventList;
    default?: V | ((a: Async) => V);
    response?: V | ((a: Async) => V);
    error?: E | ((a: Async) => E);
    resolve?: AsyncResolve<V>;
    reject?: AsyncReject<E>;
    keepResponse?: boolean;
    keepError?: boolean;
};
export declare const AsyncBreak: unique symbol;
export declare const ONCE: unique symbol;
export declare class AsyncOptions<V = any, E = any> implements IAsyncOptions<V, E> {
    constructor(options: IAsyncOptions);
    request?: AsyncFunction<V, E>;
    timeout?: number;
    loading?: boolean;
    loaded?: boolean;
    events?: AsyncEventList;
    default?: V | ((a: Async) => V);
    response?: V | ((a: Async) => V);
    error?: E | ((a: Async) => E);
    resolve?: AsyncResolve<V>;
    reject?: AsyncReject<E>;
    keepResponse?: boolean;
    keepError?: boolean;
}
export declare class Async<V = any, E = any> {
    protected readonly options: AsyncOptions;
    protected updated: boolean;
    protected timeout: number;
    constructor(request?: AsyncFunction<V, E>);
    constructor(options?: IAsyncOptions<V, E>);
    reset(): void;
    update(timeout?: number): this;
    protected checkUpdate(): void;
    readonly resolve: (response?: AsyncValue<V>) => this;
    readonly reject: (error?: AsyncValue<E>) => this;
    private get _loading();
    get loading(): boolean;
    private get _loaded();
    get loaded(): boolean;
    private get _default();
    get default(): V;
    private get _response();
    get response(): V;
    private get _error();
    get error(): E;
    private get _value();
    get value(): V;
    get events(): AsyncEventList;
    private addEvent;
    on(event: AsyncEventType | string, callback: AsyncEvent): this;
    once(event: AsyncEventType | string, callback: AsyncEvent): this;
    off(event: AsyncEventType | string, callback: AsyncEvent): this;
    trigger(event: AsyncEventType | string): this;
    then(resolve?: AsyncThen<V>, reject?: AsyncThen<E>): Promise<V>;
    catch(reject?: AsyncThen<E>): Promise<V>;
    finally(fin?: AsyncThen<V> | AsyncThen<E>): Promise<V>;
}
export default Async;
